{{- define "osp.rabbitmq" -}}
rabbitmq:
  templates:
    {{- range $name, $config := .Values.spec.rabbitmq.templates }}
    {{- if eq "replicas" $name  }}
    replicas: {{ $config }}
    {{- else }}
    {{ $name }}:
      {{- toYaml $config | nindent 4 }}
    {{- end }}
    {{- end }}
{{- end }}

{{- define "osp.memcached" -}}
memcached:
  templates:
    {{- range $name, $config := .Values.spec.memcached.templates }}
    {{ $name }}:
      replicas: {{ $config.replicas | default 3 }}
    {{- end }}
{{- end }}
