{{- define "osp.barbican" -}}
{{- if .Values.spec.barbican.enabled }}
barbican:
  enabled: {{ .Values.spec.barbican.enabled }}
  apiOverride:
    {{- toYaml .Values.spec.barbican.apiOverride | nindent 4 }}
  template:
    {{- toYaml .Values.spec.barbican.template | nindent 4 }}
{{- end }}
{{- end }}
